version: "3"

services:
  app:
    build:
      context: .
      dockerfile: ./docker_files/Dockerfile
    volumes:
      - .:/usr/src/app
      - app_poetry:/root/.cache/pypoetry
    tty: true
    environment:
      PYTHONPATH: /usr/src/app/my_scraping_tool
    command: bash -c "poetry install; /bin/bash"

  httpbin:
    image: kennethreitz/httpbin
    ports:
      - 80:80

volumes:
  app_poetry:
    external: false
