version: "3"

services:
  app:
    build:
      context: .
      dockerfile: ./docker_files/Dockerfile
    volumes:
      - .:/usr/src/app
    tty: true
    environment:
      PYTHONPATH: /usr/src/app/my_scraping_tool
    command: bash -c "poetry install; /bin/bash"

  httpbin:
    image: kennethreitz/httpbin
    ports:
      - 80:80
