version: "3"

services:
  app:
    build:
      context: .
      dockerfile: ./docker_files/Dockerfile
    volumes:
      - .:/usr/src/my_scraping_tool
      - app_poetry:/root/.cache/pypoetry
    tty: true
    environment:
      PYTHONPATH: /usr/src/my_scraping_tool/my_scraping_tool
      PYTHONDONTWRITEBYTECODE: 1
    command: bash -c "poetry install; /bin/bash"

  httpbin:
    image: kennethreitz/httpbin
    ports:
      - 80:80

  selenium_server:
    image: selenium/standalone-chrome
    ports:
      - 4444:4444
      - 7900:7900
    shm_size: "2gb"

volumes:
  app_poetry:
    external: false
